version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: leep_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-leep}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-leep_dev_pw}
      POSTGRES_DB: ${POSTGRES_DB:-leep_dev}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-leep} -d ${POSTGRES_DB:-leep_dev}"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:latest
    container_name: leep_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
